imageCredentials:
  registry: docker.com
  #pullSecrets: docker-registry-secrets
  # username: docker_user
  # password: docker_user_password
# docker image for master and slaves
images:
  master:
    repo: kaarol/jmeter-master
    tag: latest
    pullPolicy: Always
  slave:
    repo: kaarol/jmeter-slave
    tag: latest
    pullPolicy: Always

annotations: {}
config:
  enableSSL: true
  master:
    #testsConfigMap: jmeter-test
    replicaCount: 1
    restartPolicy: Always
    testType: oneShot
  slaves:
    replicaCount: 2
    restartPolicy: Always
labels: {}

influxdb:
  config:
    graphite:
      enabled: true
      bind_address: 2003
      database: jmeter
  env:
  - name: INFLUXDB_DB
    value: "jmeter"
  persistence:
    enabled: false
    # storageClass: "-"
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
    limits:
      memory: 4Gi
      cpu: 1
